export declare const SIGNAL_TREE_CONSTANTS: {
    readonly MAX_PATH_CACHE_SIZE: 1000;
    readonly LAZY_THRESHOLD: 50;
    readonly ESTIMATE_MAX_DEPTH: 3;
    readonly ESTIMATE_SAMPLE_SIZE_ARRAY: 3;
    readonly ESTIMATE_SAMPLE_SIZE_OBJECT: 5;
    readonly DEFAULT_CACHE_SIZE: 100;
    readonly DEFAULT_BATCH_SIZE: 10;
};
export declare const SIGNAL_TREE_MESSAGES: Readonly<{
    readonly NULL_OR_UNDEFINED: "null/undefined";
    readonly CIRCULAR_REF: "circular ref";
    readonly UPDATER_INVALID: "updater invalid";
    readonly LAZY_FALLBACK: "lazy fallback";
    readonly SIGNAL_CREATION_FAILED: "signal creation failed";
    readonly UPDATE_PATH_NOT_FOUND: "update path not found";
    readonly UPDATE_FAILED: "update failed";
    readonly ROLLBACK_FAILED: "rollback failed";
    readonly CLEANUP_ERROR: "cleanup error";
    readonly PRESET_UNKNOWN: "unknown preset";
    readonly STRATEGY_SELECTION: "strategy select";
    readonly TREE_DESTROYED: "destroyed";
    readonly UPDATE_TRANSACTION: "update tx";
    readonly BATCH_NOT_ENABLED: "batching disabled";
    readonly MEMOIZE_NOT_ENABLED: "memoize disabled";
    readonly MIDDLEWARE_NOT_AVAILABLE: "middleware missing";
    readonly ENTITY_HELPERS_NOT_AVAILABLE: "entity helpers missing";
    readonly TIME_TRAVEL_NOT_AVAILABLE: "time travel missing";
    readonly OPTIMIZE_NOT_AVAILABLE: "optimize missing";
    readonly UPDATE_OPTIMIZED_NOT_AVAILABLE: "update optimized missing";
    readonly CACHE_NOT_AVAILABLE: "cache missing";
    readonly PERFORMANCE_NOT_ENABLED: "performance disabled";
    readonly ENHANCER_ORDER_FAILED: "enhancer order failed";
    readonly ENHANCER_CYCLE_DETECTED: "enhancer cycle";
    readonly ENHANCER_REQUIREMENT_MISSING: "enhancer req missing";
    readonly ENHANCER_PROVIDES_MISSING: "enhancer provides missing";
    readonly ENHANCER_FAILED: "enhancer failed";
    readonly ENHANCER_NOT_FUNCTION: "enhancer not function";
    readonly EFFECT_NO_CONTEXT: "no angular context";
    readonly SUBSCRIBE_NO_CONTEXT: "no angular context";
}>;
