// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate-version-env.cjs
export const DEMO_LIBRARY_VERSIONS: Record<string, string> = {
  "signaltree": "8.0.1",
  "ngrx-store": "20.1.0",
  "ngrx-signals": "20.1.0",
  "akita": "8.0.1",
  "elf": "2.5.1",
  "ngxs": "20.1.0"
};
