// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate-version-env.cjs
export const SIGNALTREE_CORE_VERSION = '15.0.0';
export const SIGNALTREE_VERSION_SUMMARY = '@signaltree/core v15.0.0';
