// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate-version-env.cjs
export const SIGNALTREE_CORE_VERSION = '11.6.0';
export const SIGNALTREE_ENTERPRISE_VERSION = '11.6.0';
export const SIGNALTREE_VERSION_SUMMARY = '@signaltree/core v11.6.0 • enterprise v11.6.0';
