// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by tools/generate-version-env.cjs
export const SIGNALTREE_CORE_VERSION = '7.1.2';
export const SIGNALTREE_ENTERPRISE_VERSION = '7.1.2';
export const SIGNALTREE_VERSION_SUMMARY = '@signaltree/core v7.1.2 • enterprise v7.1.2';
