#!/usr/bin/env bash
# Verify that no stray dist/**/*.d.ts files exist in built packages
# These files are generated by Nx's typeDefinitions plugin but contain incorrect
# relative paths and must be excluded via package.json files array.
#
# See: .github/instructions/type-declarations-fix.md

set -e

EXIT_CODE=0

echo "🔍 Checking for stray dist/**/*.d.ts files in built packages..."

for pkg in dist/packages/*; do
  if [ ! -d "$pkg" ]; then
    continue
  fi

  PKG_NAME=$(basename "$pkg")

  # Check for any .d.ts files in the dist/ subdirectory
  if [ -d "$pkg/dist" ]; then
    FOUND_DTS=$(find "$pkg/dist" -name "*.d.ts" 2>/dev/null || true)

    if [ -n "$FOUND_DTS" ]; then
      echo "❌ ERROR: Found stray .d.ts files in $PKG_NAME/dist/"
      echo "$FOUND_DTS" | sed 's/^/    /'
      echo ""
      echo "   These files contain incorrect relative paths and break TypeScript resolution."
      echo "   Ensure package.json files array excludes 'dist/**/*.d.ts'"
      echo ""
      EXIT_CODE=1
    fi
  fi
done

if [ $EXIT_CODE -eq 0 ]; then
  echo "✅ No stray dist/**/*.d.ts files found"
else
  echo ""
  echo "💡 Fix: Update package.json files array to:"
  echo '   "files": ["dist/**/*.js", "src/**/*.d.ts", "README.md"]'
  echo ""
fi

exit $EXIT_CODE
